package io.francoisbotha.namazingserver.domain.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

@Setter
@ToString
@EqualsAndHashCode
@NoArgsConstructor
@DynamoDBTable(tableName = "Menu")
public class Menu {

    private String id;
    private Integer menuNo;
    private String menuName;
    private String menuImgUrl;
    private String menuDesc;

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    @DynamoDBAttribute
    public Integer getMenuNo() {
        return menuNo;
    }

    @DynamoDBAttribute
    public String getMenuName() {
        return menuName;
    }

    @DynamoDBAttribute
    public String getMenuImgUrl() {
        return menuImgUrl;
    }

    @DynamoDBAttribute
    public String getMenuDesc() {
        return menuDesc;
    }

}