package io.francoisbotha.namazingserver.domain.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

@Setter
@ToString
@EqualsAndHashCode
@NoArgsConstructor
@DynamoDBTable(tableName = "Vendor")
public class Vendor {

    private String id;
    private String vendorCde;
    private String vendorNo;
    private String vendorName;

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    @DynamoDBAttribute
    public String getVendorNo() {
        return vendorCde;
    }

    @DynamoDBAttribute
    public String getVendorCde() {
        return vendorCde;
    }

    @DynamoDBAttribute
    public String getVendorName() {
        return vendorName;
    }

}